language: php
php: 
  - 7.3
  
branches:
  only:
  - main

before-script: 
  - composer install

script: 
  - vendor/bin/phpunit

after_succes:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL_DISCORD

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL_DISCORD

notifications: 
  email:
    recipients:
      - $EMAIL_PXL
    on_succes: never
    on_failure: always
  
deploy: 
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: brechtcox-opsdev-calculator
  on:
    branch: main
  
