language: php
php: 
- 7.3

before-script: 
- travis_retry composer self-update
- travis_retry composer install

script: 
- vendor/bin/phpunit

notifications: 
  webhooks:
    urls:
      - $WEBHOOK_URL
    on_succes: always
    on_failure: always

branches:
  only:
  - main

