language: php
php: 
- 7.3

before-script: 
- travis_retry composer self-update
- travis_retry composer install

script: 
- vendor/bin/phpunit

notifications: 
  webhooks: https://discord.com/api/webhooks/796843083638767668/VQv-qRkZsySMfHBXb2Iw6SKAyrNAH0M-W5dhvimNBmVBUMiny_-qfyTL1JVszvufNjbn

branches:
  only:
  - main

