language: php
php: 
- 7.3

before-script: 
- composer install

script: 
- vendor/bin/phpunit

notifications: 
  email:
    recipients:
      - Brecht.cox@student.pxl.be
    on_succes: always
    on_failure: always
  
branches:
  only:
  - main

