language: php
php: 
- 7.3

before-script: 
- travis_retry composer self-update
- travis_retry composer install

script: 
- vendor/bin/phpunit

notifications: 
  email:
    - Brecht.cox@student.pxl.be
  
branches:
  only:
  - main

